query MyQuery {
  kos(where: {diskon: {_eq: true}}) {
    id
    nama
    tipe
    sisa
    thumbnail
    alamat
    harga
    harga_diskon
    Kamar_mandi_dalam
    Kamar_mandi_luar
    Kulkas
    Lemari
    Tv
  }
}
