query MyQuery ($id:uuid!) {
  kos_by_pk(id: $id) {
    thumbnail
    pict1
    pict2
    pict3
    pict4
    Kamar_mandi_dalam
    Kamar_mandi_luar
    Kulkas
    Lemari
    Tv
    alamat
    dapur
    harga
    laundry
    id
    lokasi
    luas_kamar
    nama
    denda
    pasangan
    rokok
    wifi
    harga_diskon
    diskon
    comments {
      id
      foto
      komentar
      nama
    }
  }
}
